#!/bin/bash

set -e

version=${1:-latest}
image=sclevine/nanocf:$version

nanocf_dir=$(cd `dirname "$0"` && pwd)
micropcf_dir=$nanocf_dir/micropcf
releases_dir=$micropcf_dir/images/releases

trap cleanup EXIT
function cleanup { eval "$cleanup"; }
cleanup=true

function patch_repo() {
  local patch=$nanocf_dir/patches/$(basename "$1").patch
  git -C "$1" apply "$patch"
  cleanup="${cleanup}; git -C \"$1\" apply -R \"$patch\""
}

patch_repo "$micropcf_dir"
patch_repo "$releases_dir/cf-release"
patch_repo "$releases_dir/cf-release/src/consul-release"
patch_repo "$releases_dir/diego-release"

releases='diego cf garden-linux etcd'
"$micropcf_dir/images/bosh/build" "$nanocf_dir/assets" $releases

docker build -t "$image" $@ "$nanocf_dir"
id=$(docker run -d -m 3g --privileged "$image")
docker attach "$id"
docker commit -c 'ENTRYPOINT ["/var/micropcf/run-docker"]' "$id" "$image"
