#!/bin/bash

set -e

mkdir -p /var/vcap/store

ip=$(ip route get 1 | awk '{print $NF;exit}')
echo $ip > /var/micropcf/ip
echo ${ip}.xip.io > /var/micropcf/domain
sed "s/placeholder-ip/${ip}/g" /tmp/manifest.yml > /var/micropcf/manifest.yml

apt-get -qqy install runit
/usr/sbin/runsvdir-start &
/opt/bosh-provisioner/assets/bosh-provisioner -configPath=/opt/bosh-provisioner/config.json

chmod 1777 /tmp
mv /opt/bosh-provisioner/assets/versions /var/micropcf/
rm -rf /opt/bosh-provisioner /var/vcap/data/{compile,tmp} /var/vcap/nfs
echo manual > /etc/init/runsvdir.override
apt-get -y autoremove
apt-get -y clean

/var/micropcf/reset
