#!/bin/bash

if [[ $(docker-machine inspect -f {{.Name}} nanocf) != "nanocf" ]]; then
  docker-machine create nanocf -d vmwarefusion \
    --vmwarefusion-disk-size "40000" \
    --vmwarefusion-memory-size "4096" \
    --vmwarefusion-cpu-count "-1" >&2
fi

docker-machine env nanocf
