#!/bin/bash

set -e

function usage() {
  >&2 echo "Usage:"
  >&2 echo -e "\t$0 domain [extra suite ...]"
}

if [[ $1 == '-h' ]] || [[ $1 == '--help' ]]; then
  usage && exit 0
elif [[ -z $1 ]]; then
  usage && exit 1
elif [[ ! -x /test/run ]]; then
  >&2 echo "NanoCF test directory must be present at /test."
  exit 1
fi

/test/run $@
