#!/bin/bash

set -e

assets_dir=/opt/bosh-provisioner/assets

mkdir -p /var/micropcf /var/vcap/store

ip=$(ip route get 1 | awk '{print $NF;exit}')
echo local.micropcf.io > /var/micropcf/domain
echo "$ip" > /var/micropcf/ip

sed -i "s/placeholder-ip/${ip}/g" "$assets_dir/manifest.yml"
mv "$assets_dir"/{manifest.yml,versions,scripts/*} /var/micropcf/

apt-get -qqy install runit
/usr/sbin/runsvdir-start &
"$assets_dir/bosh-provisioner" -configPath=/opt/bosh-provisioner/config.json

chmod 1777 /tmp
/var/micropcf/reset

apt-get -y autoremove
apt-get -y clean

rm -rf /opt/bosh-provisioner
find /run -name '*.pid' | xargs rm -f
